apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynapp-rs-readiness
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynapp-rs-readiness
  template:
    metadata:
      labels:
        app: mynapp-rs-readiness
    spec:
      containers:
      - name: mynapp
        image: c1t1d0s7/myweb
        readinessProbe:
          exec:
            command:
              - ls
              - /var/ready
        ports:
        - containerPort: 8080
