apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynapp-rs-dynamic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynapp-rs-dynamic
  template:
    metadata:
      labels:
        app: mynapp-rs-dynamic
    spec:
      containers:
      - name: web-server
        image: nginx:alpine
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: mynapp-pvc-dynamic
