apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mynapp-hpa-cpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mynapp-deploy-hpa
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
