apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynapp-deploy-hpa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynapp-deploy-hpa
  template:
    metadata:
      labels:
        app: mynapp-deploy-hpa
    spec:
      containers:
      - image: c1t1d0s7/myweb:v1
        name: mynapp
        resources:
          requests:
            cpu: 50m
            memory: 5Mi
          limits:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 8080
